# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages
r_packages:
  - aod
  - Formula
  - plm
  - Rdpack
  - stats
  - dplyr 
  - texreg,
  - testthat
  - knitr
  - rmarkdown
  - ggplot2
  - rmarkdown
os:
  - linux
  - osx