# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
os:
  - linux
  - osx
r:
  - oldrel
  - release
  - devel
matrix:
  exclude:
  - os: osx
    r: devel  
sudo: false
cache: packages
r_packages:
  - aod
  - Formula
  - plm
  - Rdpack
  - dplyr 
  - testthat
  - knitr
  - rmarkdown
  - ggplot2
  - rmarkdown
